spring:
  profiles:
   active:
   - dev
---
spring:
  profiles: dev
  applicatin:
    name: microservicecloud-config-zyy-test
    
---
spring:
  profiles: test
  applicatin:
    name: microservicecloud-config-zyy-test
    
